### PR TITLE
Multi languages

### PR DESCRIPTION
**Pull request by Zarh**

### CODE REVIEW

**Comment by Joonie86** [comment]
glitch

Thanks for the commit, before merging I'd like to find out why there's a glitch for default string missing [English], Could you please investigate why it causes ?

**Comment by Zarh** [comment]
I can't be sure but i think the issue come from this misstake : https://github.com/Zarh/Rebug-Toolbox/commit/828571e43587a31610ee1f383802a10e81d6856c

Can you upload me, your loc dir ?

**Comment by Joonie86** [comment]
OK your last commit fixed it, I'll merge your pull req! thanks again!

**Comment by Zarh** [comment]
Ok thanks ^^'

**Pull request merged**
